# Generated by Django 2.0.2 on 2018-02-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_hash', models.TextField(verbose_name='Previous Hash')),
                ('secret', models.TextField(verbose_name='Hash')),
                ('proof', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=250)),
                ('recipient', models.CharField(max_length=250)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='blockchain.Transaction'),
        ),
    ]
